//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "/node_modules/primeflex/primeflex.css";

import "primeicons/primeicons.css";

import "./globals.css";
import Menu from "./components/Menu/Menu";

export const metadata = {
  title: "Gestión",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="sb-nav-fixed">{children}</body>
    </html>
  );
}
